In [59]:
import pandas as pd
from pathlib2 import Path

In [87]:
def load_frame(filename):
    df = pd.read_csv(str(filename),encoding='utf-8', sep='\t', decimal=',',converters={'ags_new':str,'ags_old':str})[['ags_old','ags_new']]
    return df.set_index('ags_new')

In [88]:
p = Path('../data/output/').glob('????.csv')

In [99]:
n1, n2, n3 = list(p)[0:3]
print n1, n2, n3

ValueError: need more than 0 values to unpack

In [100]:
f1 = load_frame(n1)
f2 = load_frame(n2)
f3 = load_frame(n3)

In [101]:
t = pd.merge(f1, f2, how='outer', right_on='ags_old', left_index=True, suffixes=['2010','2011'])

In [102]:
t2 = pd.merge(t, f3, how='outer', right_on='ags_old', left_index=True, suffixes=['2011','2012'])

In [103]:
t2

           ags_old ags_old2011 ags_old2010 ags_old2011 ags_old2012
ags_new
16077036  16076087    03255003    03255003         NaN         NaN
16077036  16076087    03255016    03255016         NaN         NaN
16077036  16076087    03255017    03255017         NaN         NaN
16077036  16076087    03255020    03255020         NaN         NaN
16077036  16076087    03255025    03255025         NaN         NaN
16077036  16076087    03255032    03255032         NaN         NaN
16077036  16076087    03255005    03255005         NaN         NaN
16077036  16076087    03255019    03255019         NaN         NaN
16077036  16076087    03255031    03255031         NaN         NaN
16077036  16076087    03255033    03255033         NaN         NaN
16077036  16076087    03255035    03255035         NaN         NaN
16077036  16076087    06435014    06435014         NaN         NaN
16077036  16076087    06435028    06435028         NaN         NaN
16077036  16076087    06533015    06533015         NaN         NaN
16077036  16076087    14521150    14521150         NaN         NaN
16077036  16076087    14521150    14521650         NaN         NaN
16077036  16076087    14626180    14626550         NaN         NaN
16077036  16076087    14627060    14627350         NaN         NaN
16077036  16076087    15081030    15081030         NaN         NaN
16077036  16076087    15081030    15081175         NaN         NaN
16077036  16076087    15081030    15081260         NaN         NaN
16077036  16076087    15081030    15081270         NaN         NaN
16077036  16076087    15081030    15081315         NaN         NaN
16077036  16076087    15081030    15081390         NaN         NaN
16077036  16076087    15081030    15081460         NaN         NaN
16077036  16076087    15081030    15081470         NaN         NaN
16077036  16076087    15081030    15081520         NaN         NaN
16077036  16076087    15081030    15081595         NaN         NaN
16077036  16076087    15081030    15081065         NaN         NaN
16077036  16076087    15081030    15081250         NaN         NaN
...            ...         ...         ...         ...         ...
16065085  16065062         NaN         NaN         NaN    16065062
16065085  16065021         NaN         NaN         NaN    16065021
16065085  16065004         NaN         NaN         NaN    16065004
16065085  16065006         NaN         NaN         NaN    16065006
16065085  16065029         NaN         NaN         NaN    16065029
16065085  16065068         NaN         NaN         NaN    16065068
16065051  16065051         NaN         NaN         NaN    16065051
16068034  16068018         NaN         NaN         NaN    16068018
16069062  16069055         NaN         NaN         NaN    16069055
16069062  16069031         NaN         NaN         NaN    16069031
16069062  16069032         NaN         NaN         NaN    16069032
16069062  16069018         NaN         NaN         NaN    16069018
16069062  16069038         NaN         NaN         NaN    16069038
16069062  16069014         NaN         NaN         NaN    16069014
16069043  16069043         NaN         NaN         NaN    16069043
16069048  16069048         NaN         NaN         NaN    16069048
16070028  16070051         NaN         NaN         NaN    16070051
16070028  16070028         NaN         NaN         NaN    16070028
16071004  16071018         NaN         NaN         NaN    16071018
16071004  16071078         NaN         NaN         NaN    16071078
16071004  16071094         NaN         NaN         NaN    16071094
16071004  16071002         NaN         NaN         NaN    16071002
16071004  16071021         NaN         NaN         NaN    16071021
16072013  16072017         NaN         NaN         NaN    16072017
16072013  16072016         NaN         NaN         NaN    16072016
16073112  16073042         NaN         NaN         NaN    16073042
16073112  16073075         NaN         NaN         NaN    16073075
16076022  16076091         NaN         NaN         NaN    16076091
16076087  16076091         NaN         NaN         NaN    16076091
16077036  16077056         NaN         NaN         NaN    16077056

[1982 rows x 5 columns]

In [104]:
t2[t2['ags_old2012'].str.contains('16065085')]

ValueError: cannot index with vector containing NA / NaN values